core/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import (
    GaleryView,
    UploadImageCreateView,
    ManageListImageListView,
    UpdateImageUpdateView,
)


app_name = 'core'

urlpatterns = [
    path('', GaleryView.as_view(), name="galery"),
    path('upload/', UploadImageCreateView.as_view(), name="upload_image"),
    path('gerenciamento/', ManageListImageListView.as_view(), name="manage_list"),
    path('aprovacao/<int:pk>/', UpdateImageUpdateView.as_view(),
    name="approval_image"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

surfmappers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/models.py
import datetime
from django.db import models
from stdimage import StdImageField, JPEGField
from django.core.files.storage import default_storage


class GaleryPhoto(models.Model):
    '''That class store all photos of the applications'''
    name = models.CharField("Nome", max_length=150, null=False)
    description = models.TextField("Descrição", blank=True) 
    image_date =  models.DateField("Date", default=datetime.date.today)
    image = StdImageField("Imagem", variations={
                         'thumbnail': {'width': 300, 'height': 300, "crop": True}})
    approved = models.BooleanField("Aprovado", default=False, null=True, blank=True)
    
    class Meta:
        verbose_name = 'Galeria de Foto'
        verbose_name_plural = 'Galeria de Fotos'

    def save(self, *args, **kwargs):
        self.name = self.name.upper()
        return super(GaleryPhoto, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.name

core/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.forms import ModelForm
# from django.forms import formset_factory
from .models import GaleryPhoto


class UploadImageForm(forms.ModelForm):
    '''This class references a form before to post in the body,
    when send a new image.'''
    name = forms.CharField(max_length=150)
    description = forms.CharField(widget=forms.Textarea )
    image = forms.FileInput()

    class Meta:
        model = GaleryPhoto
        fields = ['name', 'description', 'image']


class UpdateImageForm(forms.ModelForm):
    '''This class references a action when user want left free a image'''   
    approved = forms.BooleanField(label="", initial=False, required=False)

    class Meta:
        model = GaleryPhoto
        fields = ['approved',]

core/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import FormView
from django.views.generic import ListView, CreateView, UpdateView
from django.contrib import messages
from .models import GaleryPhoto
from .forms import ( 
UploadImageForm,
UpdateImageForm,
)


class GaleryView(ListView):
    """View that show up all data inputed"""
    model = GaleryPhoto
    paginate_by = 10
    template_name = 'galery.html'

    def get_context_data(self, **kwargs):
        context = super(GaleryView, self).get_context_data(**kwargs)
        context['photos'] = GaleryPhoto.objects.filter(approved=True)
        return context


class UploadImageCreateView(CreateView):
    """Uploading a specific image"""
    model = GaleryPhoto
    form_class = UploadImageForm
    template_name = "send_image.html"

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        # Verify form is valid
        if form.is_valid():
            # Call parent form_valid to create model record object
            super(UploadImageCreateView,self).form_valid(form)
            # Add custom success message   
            messages.success(self.request, "Imagem adicionada com sucesso!")
            return HttpResponseRedirect(self.get_success_url())
        # Form is invalid
        # Set object to None, since class-based view expects model record object
        self.object = None
        print("ERRO : ", form.errors)
        messages.error(self.request, f"Ops... você precisa adicionar uma foto. ")
        # Return class-based view form_invalid to generate form with errors
        return self.form_invalid(form)

    def get_success_url(self, *args):
        return reverse('core:upload_image')


class ManageListImageListView(GaleryView):
    """List all photos to select the photos how must be on the Galery"""
    template_name = 'manage_galery.html'

    def get_context_data(self, **kwargs):
        context = super(ManageListImageListView, self).get_context_data(**kwargs)
        context['photos'] = GaleryPhoto.objects.all()
        return context


class UpdateImageUpdateView(UpdateView):
    model = GaleryPhoto
    form_class = UpdateImageForm 
    template_name = "approved_image.html"
    success_url = reverse_lazy('core:galery')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    

core/templates/approved_image.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Aprovar Imagem{% endblock %}

{% block conteudo %}
<form action="{% url 'core:approval_image' object.id %}" method="post">
{% csrf_token %}
<div class="row">
<div class="offset-md-2 col-md-10">
    <div class="row">
    <div class="class-md-5">
    <img src="{{ object.image.thumbnail.url }}" class="img-fluid" id="wrap-image" alt="Card image top">
    </div>
    <div class="class-md-6" id="info-image">
    <p class="lead ml-3 font-weight-bold">Nome : <small> {{ object.name }}</small></p>
    <p class="lead ml-3 font-weight-bold">Descrição : <small> {{ object.description }}</small> </p>
    <p class="lead ml-3 mb-0 font-weight-bold">Aprovar foto ? <span class="m-2"> {{ form }}</span> </p> 
    <small class="m-3">Clique na box caso queira aprovar a foto</small> <br>
    <a class="btn btn-warning ml-3 mt-3 mb-5 pr-4 pl-4" style="color: #fff;"
     href="{% url 'core:manage_list' %}"> Voltar</a>
    <button class="btn btn-default mt-3 mr-3 mb-5" type="submit">Salvar Alteração</button>
</div>
    </div>
    

</div>
</div> 
</form>
{% endblock %}

core/templates/galery.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %} Galeria SurfMappers{% endblock %}

{% block conteudo %}
<div class="row mb-5">
    <div class="col-md-12">
    <h2 id="galery_title">📸 Galeria de fotos do casamento 📸 </h2>
    <hr>
    <div class="row">

    {% for photo in photos %}
    <div class="col-md-3 mt-4">
        <div class="card">
            <img src="{{ photo.image.thumbnail.url }}" class="card-img-top" alt="..." >
            <div class="card-body">
              <h6 class="card-title">Nome : {{ photo.name }}</h6>
              <small id="bio-text">{{ photo.description }}</small> <br>
              <small>Data : {{ photo.image_date }}</small>
            </div>
          </div>
    </div>
    {% endfor %}

    </div> <!-- ./ second row..-->

</div> <!-- ./col-md-12 -->
</div> <!-- ./row -->

{% endblock %}

core/templates/manage_galery.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %} Galeria SurfMappers{% endblock %}

{% block conteudo %}
  <div class="row">
    <div class="col-md-12">
    <h2 id="galery_title"> Gerenciamento da galeria  </h2>
    <hr>
    <div class="row">
    {% for photo in photos %}
    <div class="col-md-3 mt-4">
        <div class="card">
            <img src="{{ photo.image.thumbnail.url }}" class="card-img-top" alt="Foto">
            <div class="card-body">
              <h6 class="card-title">Nome : {{ photo.name }}</h6>
              <small id="bio-text">{{ photo.description }}</small> <br>
              <small>Data : {{ photo.image_date }}</small>
            </div>
            <a class="btn btn-default m-2" href="{% url 'core:approval_image' photo.pk %}">
              Clique aqui para aprovar a foto </a>
          </div>
    </div>
    {% endfor %}

    <span class="mb-3">&nbsp;</span> <!-- fast solution, to responsive layout..-->
    </div> <!-- ./ second row..-->


</div> <!-- ./col-md-12 -->
</div> <!-- ./row -->
{% endblock %}

core/templates/send_image.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}Enviar Imagem{% endblock %}

{% block conteudo %}
<div class="row">
    <div class="col-md-12">
    <h2 id="weeding_title"> Adicione sua foto do casamento </h2>
    <hr>
    <form method="POST"  enctype="multipart/form-data"
    accept-charset="UTF-8" action=""> <!-- redirect to the view-->
    {% csrf_token %}
    <div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label><p class="mb-0"> Nome :  </p></label>
            <input type="text" class="form-control" name="name" placeholder="Digite os nomes dos participantes da fotos">
          </div>
    </div>
    <div class="col-md-6">
        <div class="form-group">
            <label><p class="mb-0"> Insira a foto aqui :  </p></label>
            <div class="custom-file">
                <input type="file" class="custom-file-input" name="image" id="customFile">
                <label class="custom-file-label" for="customFile">Clique aqui para adicionar a foto</label>
              </div>
          </div>
    </div>
    <div class="col-md-12">
        <div class="form-group">
            <label><p class="mb-0"> Descrição da foto :  </p></label>
            <textarea class="form-control" rows="3" name="description"
            placeholder="Descreva um momento para essa foto."></textarea>
          </div>
    </div>
    <!-- <div class="col-md-6">
        <div class="form-group">
            <div class="form-check">
                <input type="checkbox" class="form-check-input" name="approved">
                <label class="form-check-label mb-1 ml-2"><strong id="approved_text">Deseja que essa imagem apareça na galeria de fotos ? </strong></label>
              </div>
        </div>
    </div> -->
        <div class="col-md-12">
            <button class="btn btn-default pr-5 pl-5 w-100" type="submit">Clique aqui para enviar a imagem</button>
        </div>

    </div> <!-- ./ second row..-->

    

</div> <!-- ./col-md-12 -->
</div> <!-- ./row -->

{% endblock %}

templates/base.html
{%load static%}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    {% include 'parciais/_head.html' %}
    <title>Perfect Wedding | {% block titulo %}{% endblock %}</title>
</head>
<body>
      
{% include 'parciais/_nav.html' %}

{% include 'parciais/_messages.html' %}
<main role="main" id="principal" class="container border rounded p-5 bg-light shadow mb-5">
{% block conteudo %} {% endblock %}
</main>

{% include 'parciais/_footer.html' %}
{% include 'parciais/_scripts.html' %}

</body>
</html>

templates/parciais/_footer.html
{% load static %}

<div id="footer" class="container-fluid bg-dark p-3 fixed">
    <div class="container text-center">
        <p class="mb-0 text-white w-100">💞Galeria de fotos de casamento💞 - Desenvolvido por Liniker Oliveira &#169; </p>
    </div>
</div>

templates/parciais/_head.html
{% load static %}

  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css\global.css' %}">
    <link rel="stylesheet" href="{% static 'jquery\jquery-3.2.1.min.js' %}">
    <!-- Google Font: Source Sans Pro -->
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap');
    </style>
    <!--[if lt IE 9]>
        <script src="{% static 'assets/html/html5shiv.js' %}"></script>
        <script src="{% static 'assets/html/respond.min.js' %}"></script>
    <![endif]-->

templates/parciais/_messages.html
  {% load static %}
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" id='message_container' role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/parciais/_nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light mb-3" style="background-color: #E3789A; opacity: 0.8;">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        <img class="rounded" src="{% static 'img/logo.jpg' %}" alt="logo" width="80" height="50">
      </a>
    </div>
    <ul class="nav navbar-nav">
      <li class="nav-item pr-1 pl-1" id="nav-upload">
        <a class="nav-link" href="{% url 'core:upload_image' %}">
          Enviar Imagem
        </a>
      </li>
      <li class="nav-item" id="nav-">
        <a class="nav-link" href="{% url 'core:galery' %}">
          Galeria
        </a>
      </li>
      <li class="nav-item" id="nav-gerenciamento">
        <a class="nav-link" href="{% url 'core:manage_list' %}">
          Gerenciamento de Fotos
        </a>
      </li>
    </ul>
  </div>
</nav>

templates/parciais/_pagination.html
<div class="col mt-3 mb-3">
    <div class="row">
    
    <div class="pagination" >
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1">Início</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if request.GET.termo %}&termo={{ request.GET.termo }}{% endif %}">Anterior</a>
            </li>
            {% endif %}
    
            {% for page in page_obj.paginator.page_range %}
    
            {% if page_obj.number == page %}
            <li class="page-item active">
                <a class="page-link" href="?page={{ page }}{% if request.GET.termo %}&termo={{ request.GET.termo }}{% endif %}">{{ page }}</a>
            </li>
            {% elif page > page_obj.number|add:'-3' and page < page_obj.number|add:'3' %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page }}{% if request.GET.termo %}&termo={{ request.GET.termo }}{% endif %}">{{ page }}</a>
            </li>
            {% endif %}
    
            {% endfor %}
    
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if request.GET.termo %}&termo={{ request.GET.termo }}{% endif %}">Próximo</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Último</a>
            </li>
            {% endif %}
        </ul>
    </div>
    </div>
    </div>

templates/parciais/_scripts.html
{% load static %}

<script src="{% static 'jquery/jquery-3.4.1.slim.min.js' %}"></script>
<script src="{% static 'jquery/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'jquery/jquery.mask.min.js' %}"></script>


<script>
    var message_ele = document.getElementById("message_container");
    setTimeout(function () {
      message_ele.style.display = "none";
    }, 4000);
  </script>

<script>
  url = window.location.href.split('/')[3]
  $(`#nav-${url}`).addClass('active')
  if (url == "aprovacao"){
    $("#nav-gerenciamento").addClass('active')
  }
</script>